--CREATE TABLE Tables (
  --  TableID INT PRIMARY KEY IDENTITY(1,1),
  --  TableNumber INT NOT NULL UNIQUE,
  --  Capacity INT NOT NULL
--);

--CREATE TABLE Reservations (
  --  ReservationID INT PRIMARY KEY IDENTITY(1,1),
   -- TableID INT FOREIGN KEY REFERENCES Tables(TableID),
   -- CustomerName NVARCHAR(100) NOT NULL,
    --ReservationDate DATE NOT NULL,
    --ReservationTime TIME NOT NULL,
    --NumberOfGuests INT NOT NULL,
    --CreatedAt DATETIME DEFAULT GETDATE()
--  );
